//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewController
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SI2_Bom_e_BaratoEntities : DbContext
    {
        public SI2_Bom_e_BaratoEntities()
            : base("name=SI2_Bom_e_BaratoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entrega> Entrega { get; set; }
        public virtual DbSet<Fornecedor> Fornecedor { get; set; }
        public virtual DbSet<Franqueado> Franqueado { get; set; }
        public virtual DbSet<HistoricoVendas> HistoricoVendas { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<ProdVendidoPorFranqueado> ProdVendidoPorFranqueado { get; set; }
        public virtual DbSet<TipoProduto> TipoProduto { get; set; }
        public virtual DbSet<FornecedorProduto> FornecedorProduto { get; set; }
    }
}
