//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewController
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrega
    {
        public decimal franq_id { get; set; }
        public int prod_id { get; set; }
        public int valor_ped { get; set; }
        public Nullable<int> valor_forn { get; set; }
    
        public virtual Franqueado Franqueado { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
