//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewController
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdVendidoPorFranqueado
    {
        public decimal franq_id { get; set; }
        public int prod_id { get; set; }
        public decimal preco_unitario { get; set; }
        public Nullable<int> stock_total { get; set; }
        public Nullable<int> stock_min { get; set; }
        public Nullable<int> stock_max { get; set; }
        public Nullable<System.DateTime> dt_ultima_venda { get; set; }
        public Nullable<long> qtd_vendas { get; set; }
    
        public virtual Franqueado Franqueado { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
