//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewController
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.Entrega = new HashSet<Entrega>();
            this.HistoricoVendas = new HashSet<HistoricoVendas>();
            this.ProdVendidoPorFranqueado = new HashSet<ProdVendidoPorFranqueado>();
            this.FornecedorProduto = new HashSet<FornecedorProduto>();
        }
    
        public int id { get; set; }
        public string cod { get; set; }
        public string tipo { get; set; }
        public string descricao { get; set; }
        public int stock_total { get; set; }
        public int stock_min { get; set; }
        public int stock_max { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrega> Entrega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricoVendas> HistoricoVendas { get; set; }
        public virtual TipoProduto TipoProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdVendidoPorFranqueado> ProdVendidoPorFranqueado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedorProduto> FornecedorProduto { get; set; }
    }
}
